#timer for 10 sec
import time
print("10", end="")
time.sleep(1)
print("\r9", end="")
time.sleep(1)
print("\r8", end="")
time.sleep(1)
print("\r7", end="")
time.sleep(1)
print("\r6", end="")
time.sleep(1)
print("\r5", end="")
time.sleep(1)
print("\r4", end="")
time.sleep(1)
print("\r3", end="")
time.sleep(1)
print("\r2", end="")
time.sleep(1)
print("\r1", end="")
time.sleep(1)
print("\rTime-Up")
